# Import libraries

In [1]:
import ptan
import numpy as np

# Mock q values

In [2]:
q_vals = np.array([[1, 2, 3], [1, -1, 0]])
q_vals

array([[ 1,  2,  3],
       [ 1, -1,  0]])

# Argmax Action Selector

In [3]:
selector = ptan.actions.ArgmaxActionSelector()
selector(q_vals)

array([2, 0])

# Epsilon Greedy Action Selector

In [4]:
selector = ptan.actions.EpsilonGreedyActionSelector(epsilon=0.0)
selector(q_vals)

array([2, 0])

In [5]:
selector.epsilon = 1.0
selector(q_vals)

array([0, 2])

In [6]:
selector.epsilon = 0.5
selector(q_vals)

array([2, 2])

In [7]:
selector.epsilon = 0.1
selector(q_vals)

array([2, 0])

# Probability Action Selector

In [8]:
selector = ptan.actions.ProbabilityActionSelector()

print("Actions sampled from three probability distributions:")
for _ in range(10):
    acts = selector(np.array([
        [0.1, 0.8, 0.1],
        [0.0, 0.0, 1.0],
        [0.5, 0.5, 0.0],
    ]))
    
    print(acts)

Actions sampled from three probability distributions:
[1 2 0]
[1 2 1]
[1 2 1]
[1 2 1]
[1 2 1]
[1 2 0]
[1 2 1]
[0 2 0]
[1 2 1]
[1 2 0]
